title: Island Symphonies
description: Extraordinary music experiences in paradise island
sitename: Island Symphonies
baseurl: '/islandsymphonies.com'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
